### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by x0rld** [obb12/python-whatsappclient#1]
I install the module with de Makefile but there is nothing
![image](https://user-images.githubusercontent.com/45242856/73609880-1cfcce00-45d2-11ea-90a5-145a0723f6c4.png)

**Comment by obb12** [comment]
does python whatsapp.py work?

**Comment by x0rld** [comment]
nop nothing is done

**Comment by obb12** [comment]
which python version?

**Comment by x0rld** [comment]
i tried with python 2.7 and python 3.8
